-- Fase 2 — Importación inicial del catálogo a la tabla `herramientas`.
-- Fuente: vault/04 - Catalogo Completo de Recursos.md (v3.1). 97 herramientas reales.
-- Mapeo de estado: ✅=usar · 🔵=alternativa · ⚠️=verificar · ❌=descartado · 🔁=duplicado.
-- Idempotente: ON CONFLICT (lower(nombre), categoria) actualiza en vez de duplicar.

insert into public.herramientas (nombre, repo_url, para_que, categoria, estado, fase, fuente) values
-- 🧱 Cimientos / FreeEngine / optimización (F0)
('CLAUDE.md','archivo del repo','Constitución. Primer archivo. Incluye regla /rewind.','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('GitHub MCP','github.com/modelcontextprotocol','Commits automáticos.','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('Context7','npx @upstash/context7-mcp','Docs actualizadas → anti-alucinación.','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('Superpowers','github.com/obra/superpowers','TDD + planificación. Incluye find-skills.','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('Claude-Mem','github.com/thedotmack/claude-mem','Memoria entre sesiones.','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('AWS Bedrock ($200)','aws.amazon.com/bedrock','FreeEngine capa 2 (Claude). DolarApp.','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('DeepSeek vía NVIDIA','build.nvidia.com','FreeEngine capa 3. Verificar nombre modelo.','Cimientos / FreeEngine / optimización','verificar','F0','catalogo-v3.1'),
('OpenRouter','openrouter.ai','Puente a Qwen/Kimi/GLM/Minimax/DeepSeek.','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('find-skills','en Superpowers','App store de skills.','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('Security Review','github.com/anthropics/claude-code-security-review','Escaneo (nativo Claude Code).','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('Reglas Karpathy','patrón → CLAUDE.md','Reglas de elite.','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('Obsidian + Claude Code','obsidian.md','Esta bóveda.','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('OpenCode Go','github.com/sst/opencode','CLI alternativa bajo costo.','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('gstack','github.com/garrytan/gstack (106k★)','Slash-commands de roles. Opcional.','Cimientos / FreeEngine / optimización','alternativa','F0','catalogo-v3.1'),
('ECC','github.com/affaan-m/everything-claude-code','Harness skills/agentes (13 ag/43 skills).','Cimientos / FreeEngine / optimización','alternativa','F0','catalogo-v3.1'),
('Graphify','github.com/safishamsi/graphify','Grafo de código → tokens (repos 500+).','Cimientos / FreeEngine / optimización','alternativa','F0','catalogo-v3.1'),
('Bytez','bytez.com (org Bytez-com)','175-220k modelos + $200k créditos.','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('free-claude-code','github.com/Alishahryar1/free-claude-code','Proxy a modelos baratos. Parkeado.','Cimientos / FreeEngine / optimización','alternativa','F0','catalogo-v3.1'),
('Kimi Code','kimi.ai / OpenRouter','Ingeniería de volumen barata.','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('skill-vault','github.com/Hainrixz','Gestor de skills.','Cimientos / FreeEngine / optimización','alternativa','F0','catalogo-v3.1'),
('Nativas Claude Code','github.com/anthropics/claude-code','/workflow, /rewind, Ultraplan, Skill Creator, Opus 4.8.','Cimientos / FreeEngine / optimización','usar','F0','catalogo-v3.1'),
('Protocolo de Optimización de Tokens','Claude-Mem + /model opusplan + reglas concisas en CLAUDE.md','Ley de economía de tokens. Aplicar solo la capa simple en F0.','Cimientos / FreeEngine / optimización','alternativa','F0','catalogo-v3.1'),
('GitHub Store',null,'Redundante con GitHub MCP.','Cimientos / FreeEngine / optimización','descartado','F0','catalogo-v3.1'),
('Spec Kit',null,'Fusionado en Superpowers.','Cimientos / FreeEngine / optimización','duplicado','F0','catalogo-v3.1'),
-- 🤖 Orquestación de agentes (elegir 1 en F3)
('OpenClaw','Peter Steinberger (~300k★)','Agente 24/7, Telegram/WhatsApp, memoria, cron.','Orquestación de agentes','alternativa','F3','catalogo-v3.1'),
('Hermes Agent','github.com/NousResearch/hermes-agent (143k★)','Self-improving, /goal+judge, 22 plataformas, Termux.','Orquestación de agentes','alternativa','F3','catalogo-v3.1'),
('Antigravity (Google)','antigravity.google','IDE agéntico + orquestación. Gemini 3 Pro.','Orquestación de agentes','alternativa','F3','catalogo-v3.1'),
('Paperclip AI','github.com/paperclipai/paperclip','CEO Agent jerárquico. Verificar.','Orquestación de agentes','verificar','F3','catalogo-v3.1'),
('Rowboat / RuFlo','github.com/rowboatlabs/rowboat','Orquestador visual.','Orquestación de agentes','verificar','F3','catalogo-v3.1'),
('Manus','manus.ai','Agente general, pitch decks.','Orquestación de agentes','alternativa','F3','catalogo-v3.1'),
('Claude Managed Agents','Anthropic Console','Prototipado no-code.','Orquestación de agentes','alternativa','F3','catalogo-v3.1'),
('the-architect','github.com/Hainrixz','Diseña blueprints antes de construir.','Orquestación de agentes','alternativa','F3','catalogo-v3.1'),
('Agency-Agents','github.com/msitarzewski/agency-agents','147 plantillas de agentes.','Orquestación de agentes','usar','F3','catalogo-v3.1'),
('LLM Council','github.com/aiwithremy/claude-skills-llm-council','5 IAs debaten.','Orquestación de agentes','usar','F3','catalogo-v3.1'),
('Jules (Google)','jules.google.com','Agente autónomo (complementa).','Orquestación de agentes','verificar','F3','catalogo-v3.1'),
('Wingman',null,'No encontrado.','Orquestación de agentes','descartado','F3','catalogo-v3.1'),
('AutoClaw',null,'Fusionado con OpenClaw.','Orquestación de agentes','duplicado','F3','catalogo-v3.1'),
-- 💵 Automatización, WhatsApp y pagos (F1)
('n8n (Render)','github.com/n8n-io/n8n','Hub de automatización. Núcleo F1.','Automatización, WhatsApp y pagos','usar','F1','catalogo-v3.1'),
('n8n MCP','n8n MCP server','Claude Code arma los flujos por terminal.','Automatización, WhatsApp y pagos','usar','F1','catalogo-v3.1'),
('whatsapp-agentkit','github.com/Hainrixz/whatsapp-agentkit','Cerebro del vendedor WhatsApp.','Automatización, WhatsApp y pagos','usar','F1','catalogo-v3.1'),
('PagoKit','github.com/Hainrixz/agente-pagokit','Pagos (Mercado Pago/Stripe). Probar cobro test.','Automatización, WhatsApp y pagos','usar','F1','catalogo-v3.1'),
('Evolution API','github.com/EvolutionAPI/evolution-api','Gateway WhatsApp alto rendimiento.','Automatización, WhatsApp y pagos','alternativa','F1','catalogo-v3.1'),
('OpenWA','github.com/open-wa/wa-automate-nodejs','Gateway WhatsApp.','Automatización, WhatsApp y pagos','alternativa','F1','catalogo-v3.1'),
('YCloud','ycloud.com','WhatsApp API oficial.','Automatización, WhatsApp y pagos','alternativa','F1','catalogo-v3.1'),
('ManyChat','manychat.com','DMs IG → embudo.','Automatización, WhatsApp y pagos','usar','F1','catalogo-v3.1'),
-- 🛒 E-commerce y dropshipping MAYORISTA B2B (F1)
('Page Pilot AI','pagepilot.ai','Landing por lote en ~60s.','E-commerce y dropshipping MAYORISTA B2B','usar','F1','catalogo-v3.1'),
('claude-webkit','github.com/Hainrixz/claude-webkit','Landings técnicas Next.js.','E-commerce y dropshipping MAYORISTA B2B','usar','F1','catalogo-v3.1'),
('Teemdrop','teemdrop.com','Comparar precios proveedores.','E-commerce y dropshipping MAYORISTA B2B','usar','F1','catalogo-v3.1'),
('TikTok scouting','tiktok.com','Qué pedir / tendencias.','E-commerce y dropshipping MAYORISTA B2B','usar','F1','catalogo-v3.1'),
('DigitalPlat FreeDomain','digitalplat.org','Dominios gratis.','E-commerce y dropshipping MAYORISTA B2B','usar','F1','catalogo-v3.1'),
('Modelaje virtual (Kling)','kling.ai','Mostrar producto sin sesión de fotos.','E-commerce y dropshipping MAYORISTA B2B','usar','F1','catalogo-v3.1'),
('Proveedores mayoristas con catálogo',null,'Nodos de suministro. NO Combox (minorista).','E-commerce y dropshipping MAYORISTA B2B','alternativa','F1','catalogo-v3.1'),
-- 🎬 Video
('Gemini Omni / Flash / Veo','gemini.google.com','Edición por instrucción, Google Cloud.','Video','alternativa',null,'catalogo-v3.1'),
('Hunyuan Video','github.com/Tencent/HunyuanVideo','Potente y gratis (API).','Video','alternativa',null,'catalogo-v3.1'),
('Nim Video (Seedance)','nim.video','Product placement por plantilla.','Video','alternativa',null,'catalogo-v3.1'),
('Higgsfield','higgsfield.ai','UGC/cinemático + CLI/MCP.','Video','alternativa',null,'catalogo-v3.1'),
('editor-pro-max','github.com/Hainrixz','Video por código (Remotion), demos técnicas.','Video','usar',null,'catalogo-v3.1'),
('Odysser','joinodysser.com','Edición rápida (subtítulos/overlays).','Video','usar',null,'catalogo-v3.1'),
('MiniMax / Hailuo','minimax.io','Backup luxury.','Video','alternativa',null,'catalogo-v3.1'),
('LTX','github.com/Lightricks/LTX-Video','Rápido, reserva.','Video','alternativa',null,'catalogo-v3.1'),
('Invideo','invideo.io','Flujo automático.','Video','alternativa',null,'catalogo-v3.1'),
('Apify (fábrica contenido)','apify.com','Pipeline YouTube.','Video','usar',null,'catalogo-v3.1'),
-- 🖼️ Imagen, avatares y voz
('SAM 3','github.com/facebookresearch/segment-anything','Recorte de producto. F1.','Imagen, avatares y voz','usar',null,'catalogo-v3.1'),
('Real-ESRGAN','github.com/xinntao/Real-ESRGAN','Upscale fotos mayorista. F1.','Imagen, avatares y voz','usar',null,'catalogo-v3.1'),
('LivePortrait','github.com/KwaiVGI/LivePortrait','Avatar de la agencia.','Imagen, avatares y voz','usar',null,'catalogo-v3.1'),
('VibeVoice','github.com/microsoft/VibeVoice','Voz de marca $0.','Imagen, avatares y voz','usar',null,'catalogo-v3.1'),
('claude-banana','github.com/Hainrixz','Prompts de imagen.','Imagen, avatares y voz','alternativa',null,'catalogo-v3.1'),
('Nano Banana / Mindsift',null,'Avatares.','Imagen, avatares y voz','verificar',null,'catalogo-v3.1'),
('Personaplex',null,'Avatar de marca.','Imagen, avatares y voz','verificar',null,'catalogo-v3.1'),
('Napkin IA','napkin.ai','Diagramas para contenido.','Imagen, avatares y voz','usar',null,'catalogo-v3.1'),
-- 🌐 Web, UI y app
('V0.dev','v0.dev','Componentes React/Tailwind.','Web, UI y app','usar',null,'catalogo-v3.1'),
('21st.dev (Magic MCP)','21st.dev','Componentes UI alta gama vía MCP.','Web, UI y app','usar',null,'catalogo-v3.1'),
('Open CoDesign','github.com/OpenCoworkAI/open-codesign','Prompt → prototipo/slides.','Web, UI y app','usar',null,'catalogo-v3.1'),
('Rork','rork.app','Apps nativas iOS/Android.','Web, UI y app','usar',null,'catalogo-v3.1'),
('the-architect','github.com/Hainrixz','Blueprints de software.','Web, UI y app','alternativa',null,'catalogo-v3.1'),
('Claude SEO Audit','github.com/AgricDaniel/claude-seo','Auditoría SEO.','Web, UI y app','usar',null,'catalogo-v3.1'),
('Google Stitch','labs.google/stitch','UI desde lenguaje natural.','Web, UI y app','verificar',null,'catalogo-v3.1'),
('WebGL Magic / UI UX Pro Max','técnica de prompting','Estética premium F4.','Web, UI y app','usar',null,'catalogo-v3.1'),
('Blink',null,'Reemplazado por Open CoDesign/V0.','Web, UI y app','descartado',null,'catalogo-v3.1'),
-- 🔎 Scraping, research y outreach
('Playwright MCP','github.com/microsoft/playwright','Navegador estable. Outreach.','Scraping, research y outreach','usar',null,'catalogo-v3.1'),
('Firecrawl','github.com/mendableai/firecrawl','Scraping/clonar competencia.','Scraping, research y outreach','usar',null,'catalogo-v3.1'),
('Chrome DevTools MCP','github.com/ChromeDevTools/*','Scraping de webs dinámicas.','Scraping, research y outreach','alternativa',null,'catalogo-v3.1'),
('Agent-Browser','github.com/vercel-labs/agent-browser','Navegación bajo costo de tokens.','Scraping, research y outreach','alternativa',null,'catalogo-v3.1'),
('Humanizalo','github.com/Hainrixz','Evita filtros texto IA en outreach.','Scraping, research y outreach','alternativa',null,'catalogo-v3.1'),
('Comet (Perplexity)','perplexity.ai/comet','Research de Sergio.','Scraping, research y outreach','usar',null,'catalogo-v3.1'),
-- 🧠 Conocimiento (UCI) y modelos
('Gemini 1.5 Pro','aistudio.google.com','Procesar videos (2M tokens).','Conocimiento y modelos','usar',null,'catalogo-v3.1'),
('NotebookLM','notebooklm.google.com','Base de conocimiento consultable.','Conocimiento y modelos','usar',null,'catalogo-v3.1'),
('OpenWhispr','github.com/HeroTools/open-whispr','Dictado voz CEO.','Conocimiento y modelos','usar',null,'catalogo-v3.1'),
('Gemini Embedding','ai.google.dev','Memoria vectorial multimodal.','Conocimiento y modelos','usar',null,'catalogo-v3.1'),
('Kimi K2','OpenRouter','Volumen de datos.','Conocimiento y modelos','usar',null,'catalogo-v3.1'),
('Ecosistema chino (Qwen/GLM/Minimax)','OpenRouter','No instalar sueltos.','Conocimiento y modelos','usar',null,'catalogo-v3.1'),
('Mureka','mureka.ai','Música para Reels.','Conocimiento y modelos','usar',null,'catalogo-v3.1'),
('Ollama / LM Studio','github.com/ollama/ollama','Local liviano (no modelos grandes en Mac 2015).','Conocimiento y modelos','verificar',null,'catalogo-v3.1'),
-- 🖥️ Trading manual + soporte (F4)
('Mark-XXXIX',null,'Visión de pantalla en MT5/Bookmap.','Trading manual + soporte','alternativa','F4','catalogo-v3.1'),
('Databento','databento.com','Datos institucionales (bajo).','Trading manual + soporte','alternativa','F4','catalogo-v3.1'),
('Maya / maia-skill','github.com/Hainrixz','Research de inversiones (bajo).','Trading manual + soporte','alternativa','F4','catalogo-v3.1'),
('Genspark / Kimi Claw','genspark.ai','Reportes Excel/PPT.','Trading manual + soporte','usar','F4','catalogo-v3.1')
on conflict (lower(nombre), coalesce(categoria, '')) do update set
  repo_url = excluded.repo_url,
  para_que = excluded.para_que,
  estado   = excluded.estado,
  fase     = excluded.fase,
  fuente   = excluded.fuente,
  actualizado_en = now();
