-- Fase 2.1 — Seed de la taxonomía por objetivo + mapeo de las 97 herramientas.
-- Idempotente. El mapeo se hace por nombre (no hardcodea uuids).

-- ── Divisiones ─────────────────────────────────────────────
insert into public.divisiones (id, nombre, descripcion, orden) values
('crear-web','Crear webs','Todo para crear una página/sitio web.',1),
('crear-app','Crear apps','Apps móviles y prototipos.',2),
('crear-video','Crear videos','Generación y edición de video/contenido.',3),
('crear-imagen','Crear imágenes, avatares y voz','Imagen de producto, avatares y voz de marca.',4),
('automatizar','Automatizar y vender (B2B)','Automatización, WhatsApp, pagos y e-commerce mayorista.',5),
('investigar','Investigar y captar','Scraping, research y outreach.',6),
('orquestar','Orquestar agentes','Orquestadores y plantillas de agentes (se elige 1 en F3).',7),
('conocimiento','Conocimiento y voz (UCI)','Procesar conocimiento/video, dictado y memoria.',8),
('programar','Programar y extender Claude Code','Skills, repos, loops/funciones y herramientas de código.',9),
('freeengine','Motor de IA barato (FreeEngine) y memoria','Modelos baratos, razonamiento y memoria entre sesiones.',10),
('trading','Soporte al trading (F4)','Soporte al trading manual. Sin bots.',11)
on conflict (id) do update set nombre=excluded.nombre, descripcion=excluded.descripcion, orden=excluded.orden;

-- ── Subdivisiones ──────────────────────────────────────────
insert into public.subdivisiones (id, division_id, nombre, orden) values
('web-ui','crear-web','UI & componentes',1),
('web-landing','crear-web','Landing & plantillas',2),
('web-3d','crear-web','3D & visual',3),
('web-seo','crear-web','SEO',4),
('web-hosting','crear-web','Dominio & hosting',5),
('app-ui','crear-app','UI / Prototipo',1),
('app-build','crear-app','Build nativo',2),
('app-blueprint','crear-app','Blueprints',3),
('video-motor','crear-video','Motor de generación',1),
('video-edicion','crear-video','Edición & subtítulos',2),
('video-ugc','crear-video','Product placement / UGC',3),
('video-musica','crear-video','Música',4),
('video-pipeline','crear-video','Pipeline / automatización',5),
('img-producto','crear-imagen','Recorte & upscale de producto',1),
('img-avatar','crear-imagen','Avatar animado',2),
('img-voz','crear-imagen','Voz',3),
('img-prompts','crear-imagen','Prompts de imagen',4),
('auto-hub','automatizar','Hub de automatización',1),
('auto-whatsapp','automatizar','Gateway WhatsApp',2),
('auto-pagos','automatizar','Cobros / pagos',3),
('auto-dms','automatizar','DMs & embudo',4),
('auto-ecommerce','automatizar','E-commerce & proveedores',5),
('inv-scraping','investigar','Scraping',1),
('inv-navegador','investigar','Navegador',2),
('inv-research','investigar','Research',3),
('inv-outreach','investigar','Humanizar outreach',4),
('orq-orquestadores','orquestar','Orquestadores',1),
('orq-plantillas','orquestar','Plantillas de agentes',2),
('orq-consejo','orquestar','Consejo de IAs',3),
('con-procesar','conocimiento','Procesar video / conocimiento',1),
('con-dictado','conocimiento','Dictado',2),
('con-memoria','conocimiento','Memoria vectorial',3),
('prog-skills','programar','Skills & find-skills',1),
('prog-repos','programar','Repos / harnesses de GitHub',2),
('prog-loops','programar','Loops, /workflow & funciones',3),
('prog-clis','programar','Herramientas de código (CLIs)',4),
('prog-mcps','programar','MCPs base',5),
('free-modelos','freeengine','Modelos baratos',1),
('free-razonamiento','freeengine','Razonamiento',2),
('free-memoria','freeengine','Memoria entre sesiones',3),
('trad-vision','trading','Visión de pantalla',1),
('trad-datos','trading','Datos',2),
('trad-research','trading','Research de inversión',3)
on conflict (id) do update set division_id=excluded.division_id, nombre=excluded.nombre, orden=excluded.orden;

-- ── Mapeo herramienta → subdivisión (por nombre) ───────────
insert into public.herramienta_subdivision (herramienta_id, subdivision_id)
select h.id, m.sub from public.herramientas h join (values
  ('V0.dev','web-ui'),('21st.dev (Magic MCP)','web-ui'),('Open CoDesign','web-ui'),('Google Stitch','web-ui'),('WebGL Magic / UI UX Pro Max','web-ui'),('Blink','web-ui'),
  ('Page Pilot AI','web-landing'),('claude-webkit','web-landing'),
  ('WebGL Magic / UI UX Pro Max','web-3d'),
  ('Claude SEO Audit','web-seo'),
  ('DigitalPlat FreeDomain','web-hosting'),
  ('V0.dev','app-ui'),('Open CoDesign','app-ui'),
  ('Rork','app-build'),
  ('the-architect','app-blueprint'),
  ('Gemini Omni / Flash / Veo','video-motor'),('Hunyuan Video','video-motor'),('MiniMax / Hailuo','video-motor'),('LTX','video-motor'),('Modelaje virtual (Kling)','video-motor'),
  ('editor-pro-max','video-edicion'),('Odysser','video-edicion'),
  ('Nim Video (Seedance)','video-ugc'),('Higgsfield','video-ugc'),
  ('Mureka','video-musica'),
  ('Invideo','video-pipeline'),('Apify (fábrica contenido)','video-pipeline'),
  ('SAM 3','img-producto'),('Real-ESRGAN','img-producto'),
  ('LivePortrait','img-avatar'),('Personaplex','img-avatar'),
  ('VibeVoice','img-voz'),
  ('claude-banana','img-prompts'),('Nano Banana / Mindsift','img-prompts'),
  ('n8n (Render)','auto-hub'),('n8n MCP','auto-hub'),
  ('whatsapp-agentkit','auto-whatsapp'),('Evolution API','auto-whatsapp'),('OpenWA','auto-whatsapp'),('YCloud','auto-whatsapp'),
  ('PagoKit','auto-pagos'),
  ('ManyChat','auto-dms'),
  ('Page Pilot AI','auto-ecommerce'),('Teemdrop','auto-ecommerce'),('TikTok scouting','auto-ecommerce'),('Proveedores mayoristas con catálogo','auto-ecommerce'),
  ('Firecrawl','inv-scraping'),('Chrome DevTools MCP','inv-scraping'),
  ('Playwright MCP','inv-navegador'),('Agent-Browser','inv-navegador'),
  ('Comet (Perplexity)','inv-research'),
  ('Humanizalo','inv-outreach'),
  ('OpenClaw','orq-orquestadores'),('Hermes Agent','orq-orquestadores'),('Antigravity (Google)','orq-orquestadores'),('Paperclip AI','orq-orquestadores'),('Rowboat / RuFlo','orq-orquestadores'),('Manus','orq-orquestadores'),('Claude Managed Agents','orq-orquestadores'),('Jules (Google)','orq-orquestadores'),('Wingman','orq-orquestadores'),('AutoClaw','orq-orquestadores'),
  ('the-architect','orq-plantillas'),('Agency-Agents','orq-plantillas'),
  ('LLM Council','orq-consejo'),
  ('Gemini 1.5 Pro','con-procesar'),('NotebookLM','con-procesar'),('Napkin IA','con-procesar'),
  ('OpenWhispr','con-dictado'),
  ('Gemini Embedding','con-memoria'),
  ('Superpowers','prog-skills'),('find-skills','prog-skills'),('skill-vault','prog-skills'),
  ('gstack','prog-repos'),('ECC','prog-repos'),('Graphify','prog-repos'),
  ('CLAUDE.md','prog-loops'),('Security Review','prog-loops'),('Reglas Karpathy','prog-loops'),('Nativas Claude Code','prog-loops'),('Protocolo de Optimización de Tokens','prog-loops'),('Spec Kit','prog-loops'),
  ('OpenCode Go','prog-clis'),('Obsidian + Claude Code','prog-clis'),
  ('GitHub MCP','prog-mcps'),('Context7','prog-mcps'),('GitHub Store','prog-mcps'),
  ('OpenRouter','free-modelos'),('DeepSeek vía NVIDIA','free-modelos'),('Bytez','free-modelos'),('free-claude-code','free-modelos'),('Kimi Code','free-modelos'),('Kimi K2','free-modelos'),('Ecosistema chino (Qwen/GLM/Minimax)','free-modelos'),('Ollama / LM Studio','free-modelos'),
  ('AWS Bedrock ($200)','free-razonamiento'),
  ('Claude-Mem','free-memoria'),
  ('Mark-XXXIX','trad-vision'),
  ('Databento','trad-datos'),
  ('Maya / maia-skill','trad-research'),('Genspark / Kimi Claw','trad-research')
) as m(nombre, sub) on h.nombre = m.nombre
on conflict do nothing;
