-- Fase 2 — Seed del Stack Definitivo por Categoría.
-- Fuente: vault/03 - Stack Definitivo por Categoria.md (v3.0). 12 categorías + 69 ítems.
-- estado: ✅ ganador · 🔵 alternativa. Idempotente.

insert into public.stack_categorias (clave, categoria, estrategia, fase, orden) values
('A','Orquestación de agentes','En F0–F2: NINGUNO → Claude Code orquesta directo (con /workflow y /rewind nativos). Se elige UNO en F3 tras comparar estrellas/commits/issues.','F3',1),
('B','Memoria, calidad de código y optimización','Base F0: CLAUDE.md + Context7 + Superpowers + Claude-Mem. Las alternativas de optimización conviven.','F0',2),
('C','FreeEngine (modelos baratos / gratis)','Puentes: OpenRouter + Bytez + NVIDIA/DeepSeek + Bedrock. Todos válidos, se rutea según costo.','F0',3),
('D','Automatización, WhatsApp y pagos','Hub: n8n en Render (+ n8n MCP para construirlo con Claude). Gateway WhatsApp y pagos = alternativas.','F1',4),
('E','Generación y edición de video','Elegir 1 motor + 1 backup AL PRODUCIR. No instalar todos juntos.',null,5),
('F','Imagen, avatares y voz','Producto: SAM 3 + Real-ESRGAN. Avatar de marca: LivePortrait + VibeVoice.',null,6),
('G','Diseño web, UI y app','F1: Page Pilot + claude-webkit. UI avanzada: 21st.dev + V0 + Open CoDesign (F3).',null,7),
('H','E-commerce y dropshipping mayorista','Foco: mayorista B2B (capital→provincia), high-ticket. NO minorista.','F1',8),
('I','Scraping, research y outreach','Conviven: Playwright (estable) + Agent-Browser (bajo token) + Chrome DevTools MCP + Firecrawl.',null,9),
('J','Conocimiento (UCI), voz y memoria','Ganadores: Gemini 1.5 Pro + NotebookLM + OpenWhispr + Gemini Embedding.',null,10),
('K','Trading (manual + soporte de visión)','El trading lo opera Sergio a mano. No hay bots. Solo soporte.','F4',11),
('L','Utilidades y referencia','Awesome-Selfhosted, LLM Council, Mureka, Napkin IA, Genspark — disponibles como utilidades puntuales.',null,12)
on conflict (clave) do update set
  categoria = excluded.categoria, estrategia = excluded.estrategia, fase = excluded.fase, orden = excluded.orden;

insert into public.stack_items (categoria_clave, herramienta, repo_url, estado, nota, fase) values
('A','OpenClaw','Peter Steinberger (~300k★)','alternativa','Autónomo 24/7, Telegram/WhatsApp nativo, memoria, cron.','F3'),
('A','Hermes Agent','NousResearch/hermes-agent (~143k★)','alternativa','Self-improving, /goal+judge, 22 plataformas, $5 VPS, Termux. Muy alineado con AGI Telegram.','F3'),
('A','Antigravity (Google)','antigravity.google','alternativa','IDE agéntico + app de orquestación. Gemini 3 Pro, soporta Claude.','F3'),
('A','Manus','manus.ai','alternativa','Agente general, pitch decks, research.','F3'),
('A','Claude Managed Agents','Anthropic Console','alternativa','Prototipado no-code.','F3'),
('A','Paperclip / Rowboat','varios','alternativa','Verificar al llegar a F3.','F3'),
('B','CLAUDE.md','archivo del repo','ganador','Constitución. Primer archivo. Incluye regla /rewind.','F0'),
('B','Context7','npx @upstash/context7-mcp','ganador','Docs actualizadas → mata alucinaciones.','F0'),
('B','Superpowers','github.com/obra/superpowers','ganador','TDD + planificación. Incluye find-skills.','F0'),
('B','Claude-Mem','github.com/thedotmack/claude-mem','ganador','Memoria entre sesiones.','F0'),
('B','gstack','garrytan/gstack','alternativa','Slash-commands de roles (CEO/QA/Designer).',null),
('B','ECC','affaan-m/everything-claude-code','alternativa','Harness de skills/agentes. Evaluar solapamiento.',null),
('B','Graphify','safishamsi/graphify','alternativa','Grafo de código → ahorro tokens (repos 500+ archivos).',null),
('B','skill-vault','Hainrixz','alternativa','Gestor de skills.',null),
('B','Nativas Claude Code','anthropics/claude-code','ganador','/workflow, /rewind, Ultraplan, Skill Creator, Security Review.','F0'),
('C','AWS Bedrock ($200)','aws.amazon.com/bedrock','ganador','Capa 2 — razonamiento (Claude).',null),
('C','DeepSeek vía NVIDIA','build.nvidia.com','ganador','Capa 3 — operativos $0. Verificar modelo.',null),
('C','OpenRouter','openrouter.ai','ganador','Puente a Qwen, Kimi, GLM, Minimax, DeepSeek.',null),
('C','Bytez','bytez.com (org Bytez-com)','ganador','175-220k modelos + $200k créditos.',null),
('C','Kimi Code','kimi.ai / OpenRouter','ganador','Ingeniería de volumen, barato.',null),
('C','free-claude-code','Alishahryar1/free-claude-code','alternativa','Parkeado (opcional).',null),
('D','n8n (Render)','n8n-io/n8n','ganador','Hub de automatización. Núcleo F1.','F1'),
('D','n8n MCP','n8n MCP server','ganador','Claude Code arma los flujos por terminal.','F1'),
('D','PagoKit','Hainrixz/agente-pagokit','ganador','Genera pagos (Mercado Pago/Stripe). Probar cobro test.','F1'),
('D','whatsapp-agentkit','Hainrixz/whatsapp-agentkit','ganador','Cerebro del vendedor WhatsApp.','F1'),
('D','Evolution API','EvolutionAPI/evolution-api','alternativa','Gateway WhatsApp alto rendimiento.',null),
('D','OpenWA','open-wa/wa-automate-nodejs','alternativa','Gateway WhatsApp alternativo.',null),
('D','YCloud / ManyChat',null,'alternativa','API oficial WhatsApp / DMs IG.',null),
('E','Gemini Omni / Veo','gemini.google.com','alternativa','Edición por instrucción, Google Cloud.',null),
('E','Hunyuan Video','Tencent/HunyuanVideo','alternativa','Potente y gratis (API).',null),
('E','Nim Video / Higgsfield',null,'alternativa','Product placement / UGC cinemático.',null),
('E','editor-pro-max','Hainrixz','ganador','Video por código (Remotion) — demos técnicas con datos.',null),
('E','Odysser','joinodysser.com','ganador','Edición rápida (subtítulos/overlays).',null),
('E','MiniMax / LTX / Invideo',null,'alternativa','Reservas.',null),
('F','SAM 3','facebookresearch/segment-anything','ganador','Recorte de producto. F1.','F1'),
('F','Real-ESRGAN','xinntao/Real-ESRGAN','ganador','Upscale de fotos del mayorista. F1.','F1'),
('F','LivePortrait','KwaiVGI/LivePortrait','ganador','Animación del avatar de la agencia.',null),
('F','VibeVoice','microsoft/VibeVoice','ganador','Voz de marca $0.',null),
('F','claude-banana','Hainrixz','alternativa','Prompts de imagen.',null),
('F','Nano Banana / Personaplex',null,'alternativa','Avatares (verificar).',null),
('G','Page Pilot AI','pagepilot.ai','ganador',null,'F1'),
('G','claude-webkit','Hainrixz/claude-webkit','ganador',null,'F1/F2'),
('G','21st.dev (Magic MCP)','21st.dev','ganador',null,'F3'),
('G','the-architect','Hainrixz','alternativa','Blueprints.','F3'),
('G','V0.dev / Rork / Open CoDesign',null,'alternativa',null,'F3'),
('H','Page Pilot AI','pagepilot.ai','ganador',null,'F1'),
('H','Teemdrop','teemdrop.com','ganador','Comparar precios.','F1'),
('H','TikTok scouting',null,'ganador','Qué pedir.','F1'),
('H','DigitalPlat FreeDomain','digitalplat.org','ganador',null,'F0'),
('H','Proveedores mayoristas con catálogo automatizado',null,'alternativa','Nodos de suministro; NO Combox/minorista.','F1'),
('I','Playwright MCP','microsoft/playwright','ganador',null,'F1/F2'),
('I','Firecrawl','mendableai/firecrawl','ganador',null,'F2'),
('I','Chrome DevTools MCP','ChromeDevTools/*','alternativa',null,'F1/F2'),
('I','Agent-Browser','vercel-labs/agent-browser','alternativa','Bajo costo de tokens.','F1/F2'),
('I','Humanizalo','Hainrixz','alternativa','Outreach por mail.','F2'),
('I','Comet (Perplexity)',null,'ganador','Research.','F1'),
('J','Gemini 1.5 Pro','aistudio.google.com','ganador','Procesar videos.','F2'),
('J','NotebookLM','notebooklm.google.com','ganador',null,'F2'),
('J','OpenWhispr','HeroTools/open-whispr','ganador','Dictado CEO.','F1'),
('J','Gemini Embedding','ai.google.dev','ganador','Memoria vectorial.','F3'),
('J','Kimi K2','OpenRouter','ganador',null,'F3'),
('K','Mark-XXXIX',null,'alternativa','Visión de pantalla en MT5/Bookmap.','F4'),
('K','Databento','databento.com','alternativa','Datos, bajo.','F4'),
('K','Maya / maia-skill','Hainrixz','alternativa','Research, bajo.','F4'),
('L','Awesome-Selfhosted','github.com/awesome-selfhosted/awesome-selfhosted','alternativa','Utilidad puntual.',null),
('L','LLM Council','github.com/aiwithremy/claude-skills-llm-council','alternativa','5 IAs debaten.',null),
('L','Mureka','mureka.ai','alternativa','Música para Reels.',null),
('L','Napkin IA','napkin.ai','alternativa','Diagramas para contenido.',null),
('L','Genspark','genspark.ai','alternativa','Reportes Excel/PPT.',null)
on conflict (categoria_clave, lower(herramienta)) do update set
  repo_url = excluded.repo_url, estado = excluded.estado, nota = excluded.nota, fase = excluded.fase;
